# Render Blueprint
# https://render.com/docs/blueprint-spec

services:
  - type: web
    name: mlflow-server
    runtime: docker
    plan: free
    envVars:
      - key: MLFLOW_TRACKING_URI
        value: sqlite:///mlflow.db
    disk:
      name: mlflow-data
      mountPath: /app/mlruns
      sizeGB: 1
